import { useEffect, useState } from 'react'
import { ArrowRight, CheckCircle2, Circle, Loader2, Sparkles } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { useBusiness } from '../context/BusinessContext'
import { api } from '../utils/api'
import PageMeta from '../components/common/PageMeta'

const stateLabel = value => ({ ACTIVE: 'Live', COMPLETED: 'Active', IN_PROGRESS: 'In progress', REQUIRED: 'Needs setup', NOT_STARTED: 'Not started' }[value] || 'Not started')

export function BusinessEntryPage() {
  return <main className="section-wrapper py-14 sm:py-20"><PageMeta title="Business" path="/business" /><p className="eyebrow">Earnova Business</p><h1 className="page-title mt-3 max-w-2xl">Build a stronger business, one useful step at a time.</h1><p className="page-lead mt-4">Start with your business profile or open a workspace you already manage.</p><div className="mt-9 grid gap-4 md:grid-cols-3">{[['Start a business','Create a profile and roadmap.','/business/start'],['I already run a business','Bring your operations into one workspace.','/business/start'],['Grow my business','See the next action that can move you forward.','/business/dashboard']].map(([title,copy,to]) => <Link key={title} to={to} className="surface-card group p-6 hover:border-brand-300"><h2 className="text-lg font-bold text-slate-950">{title}</h2><p className="mt-2 text-sm text-slate-600">{copy}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-brand-700">Continue <ArrowRight className="h-4 w-4 group-hover:translate-x-1" /></span></Link>)}</div></main>
}

export default function BusinessJourneyPage({ mode = 'dashboard' }) {
  const { selectedBusiness, loading, createBusiness } = useBusiness()
  const [lifecycle, setLifecycle] = useState(null)
  const [error, setError] = useState('')
  const [saving, setSaving] = useState(false)
  const navigate = useNavigate()
  useEffect(() => { if (!selectedBusiness || mode === 'start') return; api.get(`/businesses/${selectedBusiness._id}/lifecycle`).then(setLifecycle).catch(err => setError(err.message)) }, [selectedBusiness, mode])
  const initialize = async () => { setSaving(true); try { await api.post(`/businesses/${selectedBusiness._id}/roadmap`, {}); setLifecycle(await api.get(`/businesses/${selectedBusiness._id}/lifecycle`)) } catch (err) { setError(err.message) } finally { setSaving(false) } }
  const create = async event => { event.preventDefault(); const form = new FormData(event.currentTarget); setSaving(true); try { const business = await createBusiness({ name: form.get('name'), description: form.get('idea'), industry: form.get('industry'), businessType: form.get('businessType'), businessModel: form.get('businessModel'), stage: form.get('stage'), initialBudget: form.get('budget') || undefined, goals: [form.get('goal')], phone: form.get('phone') }); await api.put(`/businesses/${business._id}/blueprint`, { identity: { name: form.get('name'), industry: form.get('industry'), description: form.get('idea') }, businessModel: { audience: form.get('audience'), channel: form.get('businessModel') }, goals: { primary: form.get('goal'), items: [form.get('goal')] } }); await api.post(`/businesses/${business._id}/roadmap`, {}); navigate('/start/roadmap') } catch (err) { setError(err.message) } finally { setSaving(false) } }
  if (mode === 'start') return <main className="section-wrapper max-w-2xl py-12"><PageMeta title="Start a business" noIndex /><p className="eyebrow">Business blueprint</p><h1 className="page-title mt-2">Turn your idea into an operating business.</h1><p className="page-lead mt-3">A few practical answers create your business, blueprint and roadmap.</p><form onSubmit={create} className="surface-card mt-7 grid gap-4 p-6"><label className="form-field">Business name<input required name="name" className="input-base" placeholder="Your business name" /></label><label className="form-field">Business idea<textarea required name="idea" className="input-base" placeholder="What will your business offer?" /></label><label className="form-field">Industry<input required name="industry" className="input-base" placeholder="For example, clothing retail" /></label><label className="form-field">Business type<select name="businessType" className="input-base"><option value="proprietorship">Proprietorship</option><option value="partnership">Partnership</option><option value="llp">LLP</option><option value="private_limited">Private limited</option><option value="other">Other</option></select></label><label className="form-field">Target customers<input required name="audience" className="input-base" placeholder="For example, local shoppers" /></label><label className="form-field">Starting budget (optional)<input name="budget" type="number" min="0" className="input-base" placeholder="0" /></label><label className="form-field">How will you sell?<select name="businessModel" className="input-base"><option value="online">Online</option><option value="offline">Offline</option><option value="hybrid">Online and offline</option></select></label><label className="form-field">Current stage<select name="stage" className="input-base"><option value="idea">I have an idea</option><option value="starting">I am starting</option><option value="launching">I am launching</option><option value="operating">I already operate</option><option value="growing">I am growing</option></select></label><label className="form-field">Main goal<input required name="goal" className="input-base" placeholder="For example, launch my first collection" /></label><label className="form-field">Indian mobile number<input required name="phone" className="input-base" /></label>{error && <p className="text-sm text-red-700">{error}</p>}<button disabled={saving} className="btn-primary">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />} Create my roadmap</button></form></main>
  if (loading) return <main className="section-wrapper py-16 text-sm text-slate-600">Loading business workspace…</main>
  if (!selectedBusiness) return <main className="section-wrapper py-16"><h1 className="page-title">Create your business workspace</h1><p className="page-lead mt-3">Set up a profile first, then Earnova can create your roadmap.</p><Link to="/business/start" className="btn-primary mt-6">Start a business</Link></main>
  const items = lifecycle?.roadmap || []
  if (mode === 'roadmap') return <main className="section-wrapper py-10"><PageMeta title="Business roadmap" noIndex /><p className="eyebrow">{selectedBusiness.name}</p><h1 className="page-title mt-2">Your business roadmap</h1>{!items.length ? <button onClick={initialize} disabled={saving} className="btn-primary mt-6">Create roadmap</button> : <div className="mt-7 grid gap-3 lg:grid-cols-[1fr_.7fr]"><section className="surface-card p-5">{items.map(item => <div key={item._id} className="flex gap-3 border-b border-slate-100 py-4 last:border-0"><span className={item.status === 'COMPLETED' ? 'text-emerald-600' : 'text-slate-300'}>{item.status === 'COMPLETED' ? <CheckCircle2 /> : <Circle />}</span><div className="min-w-0 flex-1"><h2 className="font-bold text-slate-900">{item.title}</h2><p className="mt-1 text-sm text-slate-600">{item.description}</p><Link className="mt-2 inline-flex text-sm font-semibold text-brand-700 hover:underline" to={item.recommendedRoute}>Open step <ArrowRight className="ml-1 h-4 w-4" /></Link></div></div>)}</section><aside className="surface-card p-5"><p className="eyebrow">Next action</p><h2 className="mt-2 text-xl font-bold">{lifecycle?.recommendation?.title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{lifecycle?.recommendation?.reason}</p><Link className="btn-primary mt-5" to={lifecycle?.recommendation?.route || '/operate'}>Continue</Link></aside></div>}</main>
  return <main className="section-wrapper py-10"><PageMeta title="Business dashboard" noIndex /><p className="eyebrow">{selectedBusiness.name}</p><h1 className="page-title mt-2">Business overview</h1>{error && <p className="mt-4 text-sm text-red-700">{error}</p>}<div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Website', lifecycle?.state?.website],['Payments', lifecycle?.state?.payments],['Products', lifecycle?.counts?.products ?? 0],['Orders', lifecycle?.counts?.orders ?? 0]].map(([label,value]) => <section key={label} className="surface-card p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-xl font-bold text-slate-950">{typeof value === 'number' ? value : stateLabel(value)}</p></section>)}</div><section className="surface-card mt-5 p-6"><p className="eyebrow">Next recommended action</p><h2 className="mt-2 text-xl font-bold">{lifecycle?.recommendation?.title || 'Create your roadmap'}</h2><p className="mt-2 text-sm text-slate-600">{lifecycle?.recommendation?.reason || 'Create a roadmap so Earnova can guide your next step.'}</p><Link to="/business/roadmap" className="btn-primary mt-5">View roadmap</Link></section></main>
}
