import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { useBusiness } from '../context/BusinessContext'
import { api } from '../utils/api'
import PageMeta from '../components/common/PageMeta'

export default function CapabilityStatusPage() {
  const { selectedBusiness, loading } = useBusiness(); const [data, setData] = useState(); const [detail, setDetail] = useState(null); const [history, setHistory] = useState([]); const [busy, setBusy] = useState('')
  const load = () => { if (!selectedBusiness) return; Promise.all([api.get(`/businesses/${selectedBusiness._id}/capabilities`), api.get(`/businesses/${selectedBusiness._id}/verification-runs`)]).then(([status, runs]) => { setData(status); setHistory(runs.runs || []) }).catch(() => setData({ capabilities: [] })) }
  useEffect(load, [selectedBusiness])
  const reverify = async key => { setBusy(key); try { await api.post(`/businesses/${selectedBusiness._id}/capabilities/${key}/reverify`, {}); load() } finally { setBusy('') } }
  const diagnose = async key => { setBusy(key); try { setDetail(await api.get(`/businesses/${selectedBusiness._id}/capabilities/${key}/diagnosis`)) } finally { setBusy('') } }
  const recovery = async () => { if (!detail) return; const result = await api.post(`/businesses/${selectedBusiness._id}/capabilities/${detail.capability}/recovery-plan`, {}); setDetail({ ...detail, plan: result.plan }) }
  if (loading) return null
  if (!selectedBusiness) return <main className="section-wrapper py-16"><Link className="btn-primary" to="/business/start">Start your first business</Link></main>
  return <main className="section-wrapper py-10"><PageMeta title="Business status" noIndex /><p className="eyebrow">Business status</p><h1 className="page-title mt-2">What is ready to operate?</h1><div className="surface-card mt-7 divide-y p-5">{(data?.capabilities || []).map(capability => <div key={capability.key} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><p className="font-semibold">{capability.key.replaceAll('_', ' ')}</p><p className="mt-1 text-xs text-slate-500">{data?.evidence?.find(item => item.capabilityKey === capability.key)?.observedAt ? `Last checked ${new Date(data.evidence.find(item => item.capabilityKey === capability.key).observedAt).toLocaleString()}` : capability.reason || 'Not configured yet'}</p></div><div className="flex items-center gap-2"><span className="status-badge status-info">{capability.state.replaceAll('_', ' ')}</span><button className="btn-secondary text-xs" disabled={busy === capability.key} onClick={() => reverify(capability.key)}>Reverify</button>{capability.state !== 'VERIFIED' && <button className="btn-secondary text-xs" disabled={busy === capability.key} onClick={() => diagnose(capability.key)}>Diagnose</button>}</div></div>)}</div>{detail && <section className="surface-card mt-5 p-5"><h2 className="font-bold">{detail.capability.replaceAll('_', ' ')} needs attention</h2><p className="mt-2 text-sm text-slate-600">{detail.primaryIssue.capability.replaceAll('_', ' ')} is {detail.primaryIssue.state.replaceAll('_', ' ').toLowerCase()}.</p><p className="mt-2 text-sm text-slate-600">Reason: {detail.reasonChain.map(item => item.replaceAll('_', ' ')).join(' → ')}</p>{!detail.plan ? <button className="btn-primary mt-4" onClick={recovery}>Create recovery plan</button> : <p className="mt-4 text-sm text-slate-600">Recovery plan created. It requires your confirmation before any external action.</p>}</section>}<section className="surface-card mt-5 p-5"><h2 className="font-bold">Recent verification activity</h2>{history.length ? history.map(run => <p key={run._id} className="mt-3 text-sm">{run.targetCapability.replaceAll('_', ' ')} · {run.executedChecks?.length || 0} checks run · {run.skippedChecks?.length || 0} reused · {run.resultingState || run.status}</p>) : <p className="mt-2 text-sm text-slate-500">No verification activity yet.</p>}</section></main>
}
