export const CA_SERVICE_CATALOG = [
  {
    slug: 'income-tax-return-filing',
    name: 'Income-tax return filing',
    category: 'Tax',
    summary: 'Prepare and file an income-tax return using the information and documents you provide.',
    whoNeedsIt: ['Individuals with taxable income', 'Salaried people with multiple income sources', 'Freelancers and proprietors'],
    eligibility: ['A valid PAN', 'Access to relevant income and tax records'],
    deliverables: ['Prepared return', 'Filing acknowledgement when filed', 'Customer-visible completion summary'],
    exclusions: ['Representation in litigation', 'Undisclosed or unsupported transactions'],
    requiredDocuments: ['PAN', 'Form 16 where applicable', 'AIS/TIS', 'Bank interest statement'],
    pricingMode: 'starting',
    startingPrice: 1250,
    handlingTime: 'Usually 3–7 business days after complete documents are accepted.',
    externalDependency: 'Income Tax Department systems and any authority response can affect timing.',
    consultationRequired: false,
    addOns: ['Capital-gains review', 'Foreign-income review', 'Notice-response support'],
    refundPolicy: 'Refund eligibility depends on work completed, third-party fees and the accepted quote.',
  },
  {
    slug: 'gst-registration',
    name: 'GST registration',
    category: 'GST',
    summary: 'Assess registration readiness, prepare the application and coordinate clarifications.',
    whoNeedsIt: ['Eligible businesses', 'Businesses registering voluntarily', 'Sellers requiring GST registration'],
    eligibility: ['Active business or proposed business', 'Authorized signatory and address records'],
    deliverables: ['Application preparation', 'Submission support', 'Registration record when approved'],
    exclusions: ['Guaranteed registration', 'Government fees or penalties unless quoted'],
    requiredDocuments: ['PAN', 'Business constitution proof', 'Address proof', 'Authorized-signatory proof'],
    pricingMode: 'quote',
    handlingTime: 'Initial review usually within 2 business days; authority processing varies.',
    externalDependency: 'Approval and processing are controlled by the GST authority.',
    consultationRequired: true,
    addOns: ['GST return assistance', 'Bookkeeping setup'],
    refundPolicy: 'Professional work already completed and government fees are generally non-refundable.',
  },
  {
    slug: 'gst-return-assistance',
    name: 'GST return assistance',
    category: 'GST',
    summary: 'Organize return data, identify gaps and support GST return preparation.',
    whoNeedsIt: ['GST-registered businesses', 'Businesses with pending return preparation'],
    eligibility: ['Active GST registration', 'Complete sales and purchase records'],
    deliverables: ['Return working', 'Exception list', 'Submission support as agreed'],
    exclusions: ['Reconstruction of missing books unless quoted', 'Guaranteed acceptance'],
    requiredDocuments: ['GST returns history', 'Sales register', 'Purchase register', 'Input-tax records'],
    pricingMode: 'quote',
    handlingTime: 'Based on return period, transaction volume and document completeness.',
    externalDependency: 'GST portal availability and authority processing.',
    consultationRequired: false,
    addOns: ['Bookkeeping', 'Reconciliation', 'Notice-response assistance'],
    refundPolicy: 'Governed by the accepted quote and completed milestones.',
  },
  {
    slug: 'tds-assistance',
    name: 'TDS assistance',
    category: 'Tax',
    summary: 'Support TDS calculation review, return preparation and correction workflows.',
    whoNeedsIt: ['Employers', 'Businesses making specified payments', 'Deductors correcting prior filings'],
    eligibility: ['Applicable TAN and payment records'],
    deliverables: ['TDS working', 'Return preparation', 'Correction guidance where included'],
    exclusions: ['Interest, penalty or government charges'],
    requiredDocuments: ['TAN', 'Deductee data', 'Payment records', 'Prior returns where applicable'],
    pricingMode: 'quote',
    handlingTime: 'Confirmed after volume and filing-period review.',
    externalDependency: 'TRACES and tax-authority systems.',
    consultationRequired: false,
    addOns: ['Payroll coordination', 'Correction return'],
    refundPolicy: 'Governed by the accepted quote and completed milestones.',
  },
  {
    slug: 'bookkeeping',
    name: 'Bookkeeping',
    category: 'Accounts',
    summary: 'Maintain structured books from customer-approved source records.',
    whoNeedsIt: ['Small businesses', 'Freelancers', 'Growing companies needing monthly books'],
    eligibility: ['Regular access to complete transaction records'],
    deliverables: ['Updated books', 'Exception list', 'Periodic summary'],
    exclusions: ['Audit opinion', 'Unsupported transaction reconstruction'],
    requiredDocuments: ['Bank statements', 'Sales records', 'Purchase and expense records'],
    pricingMode: 'retainer',
    handlingTime: 'Recurring schedule configured after onboarding.',
    externalDependency: 'Timely customer document submission.',
    consultationRequired: true,
    addOns: ['Payroll coordination', 'GST assistance', 'Financial statements'],
    refundPolicy: 'Recurring-plan and completed-period terms apply.',
  },
  {
    slug: 'payroll-coordination',
    name: 'Payroll coordination',
    category: 'Accounts',
    summary: 'Coordinate payroll inputs, checks and periodic output with your authorized team.',
    whoNeedsIt: ['Employers with recurring payroll'],
    eligibility: ['Authorized employee and attendance records'],
    deliverables: ['Payroll working', 'Exception list', 'Agreed reports'],
    exclusions: ['Employment-law representation', 'Bank salary execution unless quoted'],
    requiredDocuments: ['Employee master', 'Attendance inputs', 'Salary structure', 'Deduction inputs'],
    pricingMode: 'quote',
    handlingTime: 'Configured around the agreed monthly payroll calendar.',
    externalDependency: 'Customer approvals and complete payroll inputs.',
    consultationRequired: true,
    addOns: ['TDS assistance', 'Bookkeeping'],
    refundPolicy: 'Recurring-plan and completed-period terms apply.',
  },
  {
    slug: 'proprietorship-registration',
    name: 'Proprietorship registration support',
    category: 'Registration',
    summary: 'Coordinate relevant registrations for a proposed proprietorship.',
    whoNeedsIt: ['Individuals starting a proprietorship'],
    eligibility: ['Eligible proprietor and business address'],
    deliverables: ['Registration checklist', 'Application support for agreed registrations'],
    exclusions: ['Guaranteed approval', 'Registrations not listed in the quote'],
    requiredDocuments: ['PAN', 'Identity proof', 'Address proof', 'Business address proof'],
    pricingMode: 'quote',
    handlingTime: 'Confirmed after the required registration set is identified.',
    externalDependency: 'Relevant government and local-authority processing.',
    consultationRequired: true,
    addOns: ['GST registration', 'Bookkeeping setup'],
    refundPolicy: 'Government fees and completed professional work are non-refundable.',
  },
  {
    slug: 'partnership-support',
    name: 'Partnership support',
    category: 'Registration',
    summary: 'Support partnership documentation and agreed registration steps.',
    whoNeedsIt: ['Partners forming or updating a partnership'],
    eligibility: ['Identified partners and agreed business terms'],
    deliverables: ['Document checklist', 'Drafting coordination', 'Registration support where included'],
    exclusions: ['Dispute representation', 'Guaranteed registration'],
    requiredDocuments: ['Partner KYC', 'Business address proof', 'Agreed commercial terms'],
    pricingMode: 'quote',
    handlingTime: 'Confirmed after document and scope review.',
    externalDependency: 'Registrar, stamp and local-authority processes.',
    consultationRequired: true,
    addOns: ['GST registration', 'PAN/TAN coordination'],
    refundPolicy: 'Government fees and completed professional work are non-refundable.',
  },
  {
    slug: 'llp-registration',
    name: 'LLP registration',
    category: 'Registration',
    summary: 'Coordinate LLP incorporation preparation and agreed post-registration steps.',
    whoNeedsIt: ['Founders choosing an LLP structure'],
    eligibility: ['Eligible designated partners and approved identity records'],
    deliverables: ['Incorporation preparation', 'Filing coordination', 'Agreed registration documents'],
    exclusions: ['Guaranteed name or incorporation approval'],
    requiredDocuments: ['Partner KYC', 'Digital-signature inputs', 'Registered-office proof'],
    pricingMode: 'quote',
    handlingTime: 'Estimate provided after name, partner and document review.',
    externalDependency: 'MCA systems and registrar decisions.',
    consultationRequired: true,
    addOns: ['GST registration', 'Accounting setup', 'Annual compliance'],
    refundPolicy: 'Government fees and completed professional work are non-refundable.',
  },
  {
    slug: 'private-limited-company-registration',
    name: 'Private limited company registration',
    category: 'Registration',
    summary: 'Coordinate incorporation documents and filings for an eligible private company.',
    whoNeedsIt: ['Founders choosing a private limited structure'],
    eligibility: ['Eligible directors, shareholders and registered office'],
    deliverables: ['Incorporation preparation', 'Filing coordination', 'Agreed incorporation records'],
    exclusions: ['Guaranteed name or incorporation approval'],
    requiredDocuments: ['Director/shareholder KYC', 'Digital-signature inputs', 'Registered-office proof'],
    pricingMode: 'quote',
    handlingTime: 'Estimate provided after name, ownership and document review.',
    externalDependency: 'MCA systems and registrar decisions.',
    consultationRequired: true,
    addOns: ['GST registration', 'Accounting setup', 'Annual compliance'],
    refundPolicy: 'Government fees and completed professional work are non-refundable.',
  },
  {
    slug: 'annual-compliance',
    name: 'Annual compliance',
    category: 'Compliance',
    summary: 'Plan and coordinate agreed recurring filings for an existing entity.',
    whoNeedsIt: ['Companies and LLPs with recurring obligations'],
    eligibility: ['Active entity records and complete books'],
    deliverables: ['Obligation checklist', 'Agreed filing preparation', 'Completion summary'],
    exclusions: ['Unlisted past-period remediation', 'Guaranteed authority acceptance'],
    requiredDocuments: ['Entity master data', 'Financial records', 'Prior filings', 'Board/partner records'],
    pricingMode: 'quote',
    handlingTime: 'A case schedule is created after obligation verification.',
    externalDependency: 'Authority systems, verified statutory dates and customer approvals.',
    consultationRequired: true,
    addOns: ['Bookkeeping', 'Financial statements', 'Tax return'],
    refundPolicy: 'Governed by the accepted quote and completed milestones.',
  },
  {
    slug: 'tax-consultation',
    name: 'Tax consultation',
    category: 'Advisory',
    summary: 'Discuss a defined tax question with an appropriately verified professional.',
    whoNeedsIt: ['Individuals or businesses with a specific tax question'],
    eligibility: ['A clear question and relevant background records'],
    deliverables: ['Consultation', 'Customer-visible summary where included'],
    exclusions: ['Legal opinion', 'Guaranteed tax savings or outcome'],
    requiredDocuments: ['Question summary', 'Relevant notices or transaction summary'],
    pricingMode: 'fixed',
    handlingTime: 'Available slots depend on the selected firm and professional.',
    externalDependency: 'Advice may require additional verified facts or specialist review.',
    consultationRequired: true,
    addOns: ['Written review', 'Follow-up case'],
    refundPolicy: 'Consultation cancellation terms are shown before booking.',
  },
  {
    slug: 'financial-statements',
    name: 'Financial statements',
    category: 'Accounts',
    summary: 'Prepare financial statements from complete, reviewed accounting records.',
    whoNeedsIt: ['Businesses requiring periodic financial statements'],
    eligibility: ['Complete and reconciled books'],
    deliverables: ['Agreed financial statements', 'Open-item summary'],
    exclusions: ['Audit opinion unless separately contracted'],
    requiredDocuments: ['Trial balance', 'Ledgers', 'Bank reconciliation', 'Asset and liability schedules'],
    pricingMode: 'quote',
    handlingTime: 'Confirmed after book quality and scope review.',
    externalDependency: 'Complete customer records and clarification turnaround.',
    consultationRequired: false,
    addOns: ['Book cleanup', 'Audit support', 'Tax return'],
    refundPolicy: 'Governed by the accepted quote and completed milestones.',
  },
  {
    slug: 'notice-response-assistance',
    name: 'Notice-response assistance',
    category: 'Tax',
    summary: 'Review a notice and coordinate an appropriate response workflow.',
    whoNeedsIt: ['Recipients of a tax or compliance notice'],
    eligibility: ['Readable complete notice and related records'],
    deliverables: ['Notice review', 'Response preparation within agreed scope', 'Submission support where included'],
    exclusions: ['Guaranteed outcome', 'Litigation representation unless quoted'],
    requiredDocuments: ['Complete notice', 'Prior filings', 'Related calculations and evidence'],
    pricingMode: 'quote',
    handlingTime: 'Triage begins after the complete notice is received; statutory dates must be professionally verified.',
    externalDependency: 'Authority deadlines, portal access and response.',
    consultationRequired: true,
    addOns: ['Professional representation', 'Prior-return review'],
    refundPolicy: 'Urgent work and completed review time may be non-refundable.',
  },
  {
    slug: 'business-compliance-consultation',
    name: 'Business-compliance consultation',
    category: 'Advisory',
    summary: 'Review a business context and identify obligations requiring professional verification.',
    whoNeedsIt: ['New or growing businesses', 'Businesses changing structure or operations'],
    eligibility: ['Business profile and a defined consultation scope'],
    deliverables: ['Consultation', 'Verified action list within agreed scope'],
    exclusions: ['AI-invented deadlines', 'Legal representation', 'Guaranteed compliance'],
    requiredDocuments: ['Business profile', 'Existing registrations', 'Question summary'],
    pricingMode: 'quote',
    handlingTime: 'Scheduled after initial scope review.',
    externalDependency: 'Rules and dates must come from verified configuration or professional review.',
    consultationRequired: true,
    addOns: ['Compliance calendar setup', 'Registration support'],
    refundPolicy: 'Consultation cancellation terms are shown before booking.',
  },
]

export const SUPPORT_ISSUES = {
  ca: [
    'Cannot upload document', 'Document rejected', 'Do not understand document request',
    'Professional has not responded', 'Case has not progressed', 'Consultation rescheduling',
    'Change submitted information', 'Deliverable quality concern', 'Additional service required',
    'Payment or refund issue', 'Privacy concern', 'Professional-conduct concern', 'Other',
  ],
  business: [
    'Dashboard data issue', 'Import failure', 'Sales issue', 'Inventory issue', 'Invoice issue',
    'CRM issue', 'AI answer concern', 'Subscription issue', 'Team access issue', 'Export issue',
    'Possible data loss', 'Security concern', 'Other',
  ],
  commerce: [
    'Payment completed but order not confirmed', 'Order not processed', 'Delivery delay',
    'Incorrect item', 'Damaged item', 'Cancellation', 'Return', 'Refund', 'Invoice issue',
    'Seller complaint', 'Other',
  ],
  freelancing: [
    'Provider or client not responding', 'Work not started', 'Deadline missed', 'Quality issue',
    'Revision dispute', 'Scope dispute', 'Payment issue', 'Cancellation',
    'Inappropriate communication', 'Report user', 'Other',
  ],
  energy: [
    'Partner has not contacted customer', 'Site-visit issue', 'Quote issue',
    'Specification question', 'Installation delay', 'Installation-quality concern',
    'Warranty request', 'Subsidy-information concern', 'Payment issue', 'Report partner', 'Other',
  ],
  payments: [
    'Amount deducted but payment failed', 'Duplicate payment', 'Incorrect amount', 'Refund pending',
    'Referral commission missing', 'Provider payout pending', 'Subscription payment issue',
    'Tax invoice issue', 'Suspicious transaction', 'Other',
  ],
  account: ['Login issue', 'Profile update issue', 'Account access issue', 'Security concern', 'Privacy concern', 'Other'],
  projects: ['Purchase access issue', 'Demo access issue', 'Seller issue', 'Payment issue', 'Quality concern', 'Other'],
  referrals: ['Commission missing', 'Referral not tracked', 'Withdrawal issue', 'Other'],
}

export const SUPPORT_QUEUES = [
  'general_support', 'account_support', 'business_workspace_support', 'ca_case_support',
  'ca_professional_escalation', 'commerce_support', 'freelancing_disputes', 'energy_support',
  'payment_review', 'referral_review', 'privacy_data_requests', 'security_incident_review',
  'abuse_trust',
]

export const HELP_CATEGORIES = [
  ['account', 'Account & access'],
  ['business', 'Business Workspace'],
  ['ca', 'CA services'],
  ['freelancing', 'Freelancing'],
  ['orders', 'Orders & shopping'],
  ['projects', 'Projects'],
  ['energy', 'Energy'],
  ['payments', 'Payments & refunds'],
  ['referrals', 'Referrals'],
  ['privacy-security', 'Privacy & security'],
  ['report-abuse', 'Report abuse'],
]

export const DEFAULT_HELP_ARTICLES = [
  {
    slug: 'start-and-track-ca-service',
    title: 'How to start and track a CA service',
    service: 'ca',
    category: 'Cases',
    summary: 'Choose a service, submit a case and follow its next required action.',
    content: 'Open CA Services, review the service scope and start a request. Your case workspace shows the assigned firm, current status and whether the next action belongs to you, the firm or an external authority. Use Get Help from the case if progress or document instructions are unclear.',
    searchKeywords: ['CA case', 'start service', 'track case'],
  },
  {
    slug: 'safe-document-uploads',
    title: 'Uploading documents safely',
    service: 'privacy-security',
    category: 'Documents',
    summary: 'Learn which files are accepted and how private document access works.',
    content: 'Upload documents only inside the authorized case or support workspace. Earnova validates file type and stores sensitive files through private storage. Do not send PAN, Aadhaar, banking or tax documents through public links or ordinary email.',
    searchKeywords: ['upload', 'private documents', 'file security'],
  },
  {
    slug: 'payment-completed-order-missing',
    title: 'Payment completed but order is not confirmed',
    service: 'payments',
    category: 'Payment review',
    summary: 'What to do when money was deducted but the order is not visible.',
    content: 'Check My Orders first and avoid paying again. Start a Payment support request and select the affected order when available. Earnova verifies payment records server-side before changing an order.',
    searchKeywords: ['money deducted', 'order missing', 'payment failed'],
  },
  {
    slug: 'business-workspace-data-help',
    title: 'Get help with Business Workspace data',
    service: 'business',
    category: 'Workspace',
    summary: 'Report imports, sales, inventory, invoice or analytics concerns with safe context.',
    content: 'Use Get Help from the affected workspace page. Describe the issue without pasting passwords, tokens or complete sensitive customer records. The support request records only the safe route and authorized business context.',
    searchKeywords: ['dashboard', 'import', 'sales', 'inventory', 'invoice', 'AI'],
  },
  {
    slug: 'refund-review-process',
    title: 'How refund reviews work',
    service: 'payments',
    category: 'Refunds',
    summary: 'Understand what information is needed for a payment or refund review.',
    content: 'Refund eligibility depends on the purchased service, completed work, third-party charges and the applicable policy. Open a support request linked to the relevant order or case. Do not share full card, bank or identification numbers.',
    searchKeywords: ['refund pending', 'refund policy', 'payment review'],
  },
  {
    slug: 'report-security-privacy-concern',
    title: 'Report a security or privacy concern',
    service: 'privacy-security',
    category: 'Urgent reporting',
    summary: 'Use the restricted security or privacy queue for suspected unauthorized access or exposure.',
    content: 'If you suspect account takeover, unauthorized access or sensitive-document exposure, open an urgent security request. Do not attach unrelated sensitive documents. Earnova calculates final priority and routes the report to a restricted queue.',
    searchKeywords: ['security', 'privacy', 'account takeover', 'document exposure'],
  },
]
