import Supplier from '../models/Supplier.js'; import RFQ from '../models/RFQ.js'; import SupplierQuotation from '../models/SupplierQuotation.js'; import BusinessEvent from '../models/BusinessEvent.js'
const own=uid=>Supplier.findOne({owner:uid})
export const profile=async(req,res)=>res.json({success:true,supplier:await own(req.user._id)})
export const saveProfile=async(req,res)=>{const name=String(req.body.name||'').trim();if(!name)return res.status(400).json({success:false,message:'Supplier name is required.'});const supplier=await Supplier.findOneAndUpdate({owner:req.user._id},{$set:{name,categories:Array.isArray(req.body.categories)?req.body.categories.slice(0,20):[],location:String(req.body.location||''),offerings:Array.isArray(req.body.offerings)?req.body.offerings.slice(0,30):[],moq:String(req.body.moq||''),leadTime:String(req.body.leadTime||'')},$setOnInsert:{owner:req.user._id}},{upsert:true,new:true,runValidators:true});res.json({success:true,supplier})}
export const eligible=async(req,res)=>{const supplier=await own(req.user._id);if(!supplier)return res.status(400).json({success:false,message:'Create supplier profile first.'});const filter={status:{$in:['OPEN','QUOTED']}};if(supplier.categories?.length)filter.category={$in:supplier.categories};res.json({success:true,rfqs:await RFQ.find(filter).select('-user').sort('-createdAt').lean()})}
export const rfq=async(req,res)=>{const supplier=await own(req.user._id);const item=supplier&&await RFQ.findOne({_id:req.params.rfqId,status:{$in:['OPEN','QUOTED']}}).select('-user').lean();if(!item)return res.status(404).json({success:false,message:'RFQ not found.'});res.json({success:true,rfq:item})}
export const quotes=async(req,res)=>{const supplier=await own(req.user._id);res.json({success:true,quotes:supplier?await SupplierQuotation.find({supplier:supplier._id}).populate('rfq','title category quantity unit status').sort('-createdAt').lean():[]})}
export const submit=async(req,res)=>{const supplier=await own(req.user._id);const item=supplier&&await RFQ.findOne({_id:req.params.rfqId,status:{$in:['OPEN','QUOTED']}});if(!item)return res.status(404).json({success:false,message:'RFQ not found.'});const quantity=Number(req.body.quantity||item.quantity),unitPrice=Number(req.body.unitPrice);if(!Number.isFinite(quantity)||quantity<1||!Number.isFinite(unitPrice)||unitPrice<0)return res.status(400).json({success:false,message:'Quantity and unit price required.'});const quote=await SupplierQuotation.findOneAndUpdate({rfq:item._id,supplier:supplier._id},{$set:{business:item.business,quantity,unitPrice,totalPrice:Number(req.body.totalPrice)||quantity*unitPrice,moq:Number(req.body.moq)||undefined,leadTimeDays:Number(req.body.leadTimeDays)||undefined,deliveryEstimate:String(req.body.deliveryEstimate||''),notes:String(req.body.notes||''),validUntil:req.body.validUntil||undefined,status:'SUBMITTED'}},{upsert:true,new:true,runValidators:true});if(item.status==='OPEN'){item.status='QUOTED';await item.save()}await BusinessEvent.create({business:item.business,actor:req.user._id,eventType:'SUPPLIER_QUOTE_SUBMITTED',source:'source',metadata:{rfqId:item._id,quoteId:quote._id}});res.status(201).json({success:true,quote})}
export const withdraw=async(req,res)=>{const supplier=await own(req.user._id);const quote=supplier&&await SupplierQuotation.findOneAndUpdate({_id:req.params.quoteId,supplier:supplier._id,status:{$in:['DRAFT','SUBMITTED']}},{status:'WITHDRAWN'},{new:true});if(!quote)return res.status(404).json({success:false,message:'Quote not found.'});res.json({success:true,quote})}
export const businessQuotes=async(req,res)=>res.json({success:true,quotes:await SupplierQuotation.find({business:req.business._id,rfq:req.params.rfqId}).populate('supplier','name location verificationStatus').sort('totalPrice').lean()})
export const accept=async(req,res)=>{const quote=await SupplierQuotation.findOne({_id:req.params.quoteId,business:req.business._id,status:'SUBMITTED'});if(!quote)return res.status(404).json({success:false,message:'Quote not found.'});await SupplierQuotation.updateMany({rfq:quote.rfq,_id:{$ne:quote._id},status:'SUBMITTED'},{$set:{status:'REJECTED'}});quote.status='ACCEPTED';await quote.save();await RFQ.findOneAndUpdate({_id:quote.rfq,business:req.business._id},{$set:{status:'ACCEPTED',acceptedSupplier:quote.supplier,acceptedQuotation:quote._id}});await BusinessEvent.create({business:req.business._id,actor:req.user._id,eventType:'SUPPLIER_QUOTE_ACCEPTED',source:'source',metadata:{quoteId:quote._id,rfqId:quote.rfq}});res.json({success:true,quote})}
export const reject=async(req,res)=>{const quote=await SupplierQuotation.findOneAndUpdate({_id:req.params.quoteId,business:req.business._id,status:'SUBMITTED'},{$set:{status:'REJECTED'}},{new:true});if(!quote)return res.status(404).json({success:false,message:'Quote not found.'});res.json({success:true,quote})}
