export const CAPABILITIES={PUBLIC_WEB_PRESENCE:[],PRODUCT_AVAILABILITY:[],PAYMENT_ACCEPTANCE:[],ORDER_CAPTURE:[],FULFILMENT:[],SELL_ONLINE:['PUBLIC_WEB_PRESENCE','PRODUCT_AVAILABILITY','PAYMENT_ACCEPTANCE','ORDER_CAPTURE','FULFILMENT']}
export const TTL={PUBLIC_WEB_PRESENCE:15*60e3,PAYMENT_ACCEPTANCE:60*60e3,PRODUCT_AVAILABILITY:15*60e3,ORDER_CAPTURE:60*60e3,FULFILMENT:60*60e3}
export const evidenceState=e=>!e||e.normalizedStatus==='UNKNOWN'?'UNCONFIGURED':e.normalizedStatus==='FAILED'?'FAILED':e.expiresAt&&new Date(e.expiresAt)<new Date()?'STALE':e.normalizedStatus==='VALID'?'VERIFIED':'UNKNOWN'
export const derive=(key,states)=>{const deps=CAPABILITIES[key]||[];if(!deps.length)return states[key]||'UNCONFIGURED';const values=deps.map(d=>states[d]||'UNCONFIGURED');if(values.includes('FAILED'))return 'DEGRADED';if(values.includes('STALE'))return 'STALE';if(values.includes('UNCONFIGURED'))return 'BLOCKED';return values.every(v=>v==='VERIFIED')?'VERIFIED':'UNKNOWN'}
export const invalidatedBy={DOMAIN_CHANGED:['PUBLIC_WEB_PRESENCE'],DEPLOYMENT_COMPLETED:['PUBLIC_WEB_PRESENCE'],PAYMENT_CONFIG_CHANGED:['PAYMENT_ACCEPTANCE'],PRODUCT_CHANGED:['PRODUCT_AVAILABILITY'],INVENTORY_CHANGED:['PRODUCT_AVAILABILITY'],SHIPPING_CONFIG_CHANGED:['FULFILMENT']}
export const descendants=(keys)=>{const affected=new Set(keys);let changed=true;while(changed){changed=false;for(const [node,deps] of Object.entries(CAPABILITIES))if(deps.some(d=>affected.has(d))&&!affected.has(node)){affected.add(node);changed=true}}return [...affected]}
export const verificationPlan=(target,states={},graph=CAPABILITIES)=>{const seen=new Set(),active=new Set(),plan=[];const visit=k=>{if(active.has(k))throw new Error('Capability graph cycle detected.');if(seen.has(k)||states[k]==='VERIFIED')return;active.add(k);(graph[k]||[]).forEach(visit);active.delete(k);seen.add(k);plan.push(k)};visit(target);return plan}
export const executeVerificationPlan=async(target,states={},adapters={},graph=CAPABILITIES)=>{const plan=verificationPlan(target,states,graph);const executed=[];for(const key of plan){const adapter=adapters[key];if(!adapter)continue;const result=await adapter.collect();const normalized=adapter.normalize?adapter.normalize(result):result;states[key]=normalized;executed.push(key)}return {plan,executed,states}}
export const isolateFault=(target,states)=>{const chain=[target];let current=target;while((CAPABILITIES[current]||[]).length){const next=CAPABILITIES[current].find(k=>['FAILED','DEGRADED','BLOCKED','STALE','UNCONFIGURED'].includes(states[k]));if(!next)break;chain.push(next);current=next}return {target,chain,root:chain.at(-1),unaffected:Object.keys(states).filter(k=>!chain.includes(k)&&states[k]==='VERIFIED')}}
export const recoveryPlan=fault=>({target:fault.target,steps:[`Review ${fault.root.replaceAll('_',' ').toLowerCase()} configuration.`,`Apply the smallest approved repair.`,`Reverify ${fault.root.replaceAll('_',' ').toLowerCase()}.`,`Reverify ${fault.target.replaceAll('_',' ').toLowerCase()}.`],requiresConfirmation:true})
export const explainFault=fault=>`Earnova found an issue affecting ${fault.target.replaceAll('_',' ').toLowerCase()}: ${fault.chain.slice(1).map(x=>x.replaceAll('_',' ').toLowerCase()).join(' → ')||'configuration needs review'}.`
